---
- name: Install grafana with influxdb integration
  hosts: osiris
  vars: 
    oracle_db_port_value : 1521
   
  tasks:
    - name: Create python virtual environment and install dependencies 
      pip:
        name: requests
        virtualenv: /tmp/grafana-influx-integrator
        virtualenv_command: /usr/bin/python3 -m venv
    - name: execute grafana influx integration script
      script: hello_world.py
      args:
        executable: /tmp/grafana-influx-integrator/bin/python3

    - name: start docker
      become: yes
      service:
        name=docker
        state=started
        enabled=yes
    - name: Create a influx data volume
      community.docker.docker_volume:
        name: influx-data
    - name: Create a influx config volume
      community.docker.docker_volume:
        name: influx-config
    - name: Create a influx container container
      community.docker.docker_container:
        name: influxdb2
        image: influxdb:latest
        volumes:
          - influx-data:/var/lib/influxdb2
          - influx-config:/etc/influxdb2
        env:
          DOCKER_INFLUXDB_INIT_MODE: "setup"
          DOCKER_INFLUXDB_INIT_USERNAME: "christian"
          DOCKER_INFLUXDB_INIT_PASSWORD: "geheimespasswort"
          DOCKER_INFLUXDB_INIT_ORG: "phobosys"
          DOCKER_INFLUXDB_INIT_BUCKET: "cloudsensor"
        published_ports:
          - 8086:8086
    - name: Wait for influxdb to be available
      shell: docker exec influxdb2 influx auth list --json
      register: result
      until: result.stderr.find("Error") == -1
      retries: 10
      delay: 3
    - name: Fetch influxdb user token
      shell: docker exec influxdb2 influx auth list --json | jq -r '.[0].token'
      register: influxdb_token
    - name: Print influx token to console
      ansible.builtin.debug:
        msg: Influxdb user token {{ influxdb_token.stdout }}