---
- name: Install grafana with influxdb integration
  hosts: osiris
  vars: 
    oracle_db_port_value : 1521
   
  tasks:    
    - name: Print message
      ansible.builtin.debug:
        msg: Hello world